name: Node.js CI

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BITBUCKET_BASE_URL: ${{ secrets.BITBUCKET_BASE_URL }}
      BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
      - run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - run: pnpm run build --noEmit
        continue-on-error: true
      - run: pnpm run lint
      - run: pnpm run test run
      - run: pnpm run dev
        continue-on-error: true
